### ISSUE TITLE
Public releases and release candidates should be packaged for older Linux distributions

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#145]
Currently our 'releases' for Linux don't run on CentOS 7 for example.

We will need an automated build process to package Trillek for lots of different distros and versions of distros.

We could also look into snap/flatpak.

**Comment by milesrout** [comment]
This is related to #144

**Comment by danielekmann** [comment]
All third-party dependencies are linked statically, so this already resolves a lot of distribution issues. Was this intentional?

Not sure if #144 is entirely related. It seems to be about the CI builds being built with a too recent version of GCC, causing ABI incompatibility. Maybe we should consider using [a different compiler](https://www.appveyor.com/docs/linux-images-software/#compilers).

**Comment by adam4813** [comment]
Yeah static was intentional for the releases as the barrier to use is much lower. Once the build process was fixed and more actual development had started the goal was to refine the build process more or expand the docs on how to build it in other ways so that older linux, for example, could play.

**Comment by adam4813** [comment]
@milesrout is this still something to work towards, or what's the thoughts on it?

I am just trying to remove stale issues (even if they maybe still valid) just to help with focus on the now.

**Comment by milesrout** [comment]
You can filter out stale issues in searches. I do not think we should get rid of issues just because they're a bit old if they're still valid.
