### ISSUE TITLE
Replace/Fix spdlog or implement a simple logger

### ISSUE THREAD

**Issue by Zardoz89** [trillek-team/tec#56]
Looks that spdlog clash badly with ASIO. ASIO have a higher priority over spdlog, so would be necessary try to fix spdlog or replace it.

List of requisites that should have a logger for us : 

- Multi-thread safe (a lock-free queue ? https://github.com/gabime/spdlog/blob/1bd10957cb47824c0e24859db2bd637e472ab97d/include/spdlog/details/mpmc_bounded_q.h )
- Lightweight, we not need something with same level of bells and whistles that log4j
- A way to write simple messages for different levels : errors, warnings, normal output and debug/trace messages.
- A way to setup the log level output (ie, disable/enable debug and trace messages)
- Log output to : 
  - Errors and warnings should go to cerr (standard error output)
  - Normal and debug/trace to cout
  - All messages go to GUI Console
  - On a future, a way to write logs to a file. Because, when we have a server working, would be nice to read logs to track any issue or problem.
- Optionally, a simple way to indicate from what class was the log write (errors, warnings and debug/trace), so could be filtered.

**Comment by Zardoz89** [comment]
I'm taking a look how do a simple lightweight logger for our needs. I could do a try to doing it.

**Comment by milesrout** [comment]
Assigned you @Zardoz89 as per your comment. 

(Accidentally assigned myself first because the GitHub Issues interface is balls).

**Comment by gabime** [comment]
@Zardoz89 could you provide details on how it clashes with ASIO? I would lke to fix this issue in spdlog

**Comment by adam4813** [comment]
If I include asio before spdlog, spdlog throws and error about
GetDynamicTimzone being undefined because asio defines the windows version
to a low number for windows xp compatibility, but that number is to low
causing GetDynamicTimzone to be conditionally not compiled. The opposite
happens if I include spdlog before asio. Spdlog is including windows.h in a
way that causes winsock.h to be included that asio doesn't like and it
errors saying that winsock.h has already been included.

The solution was a preprocessor define of _WIN32_WINNT=600 (number might
need tweaking).

**Comment by gabime** [comment]
A quick fix would be to comment out line #170 in spdlog/details.os.h (and not use the z flag in the log pattern)

**Comment by adam4813** [comment]
I am going to close this issue for now as a fix is there, albeit not a pretty one.

**Comment by milesrout** [comment]
@adam4813 Is the fix actually implemented?

**Comment by adam4813** [comment]
Derp. I realized I forgot to push it. I will push it later tonight.

**Comment by adam4813** [comment]
Actually I did commit this on my fork in the networking branch.
